# Global options
baseurl = "cogsci-interpretability.github.io"
canonifyurls = true
languagecode = "en"
theme = "mrl-iclr-2023-theme"
disableKinds = ["taxonomyTerm"]

# Params that are used in <head>
[params]
  supertitle = "First Workshop on"
  title = "Cognitive Science and AI Interpretability"
  subtitle = "Dec. 6 @ NeurIPS 2025"
  author = "Jenn Hu, Eric Bigelow, Ekdeep Singh Lubana, Ellie Pavlick, XXXXXX"
  description = "First Workshop on Cognitive Science and AI Interpretability (NeurIPS 2025)"
  keywords = ["workshop", "cognitive science", "AI interpretability"]

# Options for Markdown renderer
[markup.goldmark.renderer]
  unsafe = true
  xHTML = true

# Main menu
[[menu.main]]
    name = "About"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "Call for Papers"
    url  = "/call-for-papers"
    weight = 2
[[menu.main]]
    name = "Schedule"
    url  = "/schedule"
    weight = 3
[[menu.main]]
    name = "Speakers"
    url  = "/speakers"
    weight = 4
[[menu.main]]
    name = "Organizers"
    url  = "/organizers-reviewers"
    weight = 5
# [[menu.main]]
#     name = "Formatting Instructions"
#     url  = "/formatting-instructions"
#     weight = 3
# [[menu.main]]
#     name = "Dates"
#     url  = "/#dates"
#     weight = 3
# [[menu.main]]
# name = "Accepted Papers"
# url  = "/accepted-papers"
# weight = 8
# [[menu.main]]
#     name = "Slides and Recording"
#     url  = "/slides-recording"
#     weight = 9
